package ru.myfirstwebsite.controller.command.impl;

public enum PagePath {

    USER, ERROR, REGISTRATION, VIEW_APPLICATION, VIEW_ROOM, RESULT, RENT_ROOM, APPLICATION,
    UPDATE_APPLICATION, DELETE_APPLICATION, INDEX, APPLICATION_DELETE
}
